### ISSUE TITLE
Mac / iOS Platform and Mach-O Parser

### ISSUE THREAD

**Issue by rickmark** [Vector35/platform-mac#1]
Just wanted to provide some feedback here.

Because almost all of Binary Ninja's handling of platform types is in Mach-O parser and those types are not defined here in the platform there's little opportunity to be able to meaningfully change, improve or extend the macOS / iOS platform.

When a Mach-O is loaded about 22 system types for Mach-O objects are included in the binary view.  If those type definitions were instead moved into this plugin and the Mach-O parser called the platform to define those types, we would be able to modify and PR this project to add missing system types.

Is there any way to make the Mach-O type definitions part of this plugin if the Mach-O parser remains open source?

**Comment by fuzyll** [comment]
We open-sourced the Mach-O parser entirely on Jan 26, 2023 and it can be found [here](https://github.com/Vector35/view-macho). Going to close this ticket as I believe that should address the issue. Please feel free to re-open with additional context if I'm wrong.
